version: "3"
services:
  order:
    image: fjong1/test:order-aws
    ports:
      - 8000:8000
    environment: 
      - Server=13.57.246.180
      - Database=burger
      - Collection=order
      - User=mongo_admin
      - Pass=cmpe281

volumes:
  schemas:
    external: false
