export const actionTypes = {
    UPDATE_MENU_LIST: "UPDATE_MENU_LIST",
    RESTAURANT_LIST: "RESTAURANT_LIST",
    UPDATE_CART: "UPDATE_CART",
    USER_LIST:"USER_LIST",
    REMOVE_CART_DATA_AFTER_PAYMENT: "REMOVE_CART_DATA_AFTER_PAYMENT"
};
